@echo off echo Starting backend API in first console... 
start cmd /k dotnet run --project ./src/ToDoListManagement.API 
echo Starting frontend server in second console... 
start cmd /k "cd ./frontend/ && npm run dev"
echo Launching Google Chrome... 
timeout /t 5 /nobreak 
start chrome "http://localhost:5173/"